name: Release
on:
  push:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup

      - name: Build
        run: bun run build

      - name: Create Release
        id: changeset
        uses: changesets/action@v1.4.1
        with:
          commit: "chore(release): 📦 version packages"
          title: "chore(release): 📦  version packages"
          publish: bunx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Fix formatting
        if: steps.changeset.outputs.hasChangesets == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout changeset-release/main
          bun lint:fix
          git add .
          # Check if there are staged changes before committing and pushing
          if ! git diff --staged --quiet; then
            git commit -m "chore(release): 📦 fix formatting"
            git push origin changeset-release/main
          else
            echo "No formatting changes to commit."
          fi
