name: Release
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  checks:
    uses: ./.github/workflows/main.yml
  release:
    runs-on: ubuntu-latest
    needs: [checks]
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup

      - name: Build
        run: bun build:packages

      - name: Create Release
        id: changeset
        uses: changesets/action@v1.4.1
        with:
          commit: "chore(release): 📦 version packages"
          title: "chore(release): 📦  version packages"
          publish: bunx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Fix formatting
        if: steps.changeset.outputs.hasChangesets == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout changeset-release/main
          bun lint:fix
          git add .
          # Check if there are staged changes before committing and pushing
          if ! git diff --staged --quiet; then
            git commit -m "chore(release): 📦 fix formatting"
            git push origin changeset-release/main
          else
            echo "No formatting changes to commit."
          fi
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    needs: [release]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/setup

      - name: Install Vercel CLI
        run: bun install --global vercel@latest

      - name: Pull environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish!
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
